/**
 * MCP v1 endpoint catalog — single source of truth for GET /api/mcp/v1/catalog.
 * Every exposed MCP route must be documented here.
 */

const AUTH_BOTH = ['X-API-Key', 'Bearer'];
const AUTH_KEY = ['X-API-Key'];

const COMMON_ERRORS = [
  { status: 401, message: 'Invalid or missing credentials.' },
  { status: 422, message: 'The given data was invalid.' },
  { status: 429, message: 'Too many requests. Please try again later.' },
];

const PAGINATION_PARAMS = [
  { name: 'page', in: 'query', type: 'integer', required: false, description: 'Page number (default 1)' },
  { name: 'per_page', in: 'query', type: 'integer', required: false, description: 'Items per page', rules: 'min:1|max:200' },
];

const SORT_PARAMS = [
  { name: 'sort_by', in: 'query', type: 'string', required: false, description: 'Column to sort by' },
  { name: 'sort_order', in: 'query', type: 'string', required: false, description: 'Sort direction: asc or desc' },
];

export function getMcpV1Endpoints() {
  return [
    {
      method: 'GET',
      path: '/api/mcp/v1/catalog',
      description: 'Discover all MCP v1 endpoints available in EMZI Nexus Booking.',
      auth: AUTH_BOTH,
      params: [],
      request_example: 'GET /api/mcp/v1/catalog',
      response_example: {
        success: true,
        message: null,
        data: [{ method: 'GET', path: '/api/mcp/v1/catalog', description: 'Discover all MCP v1 endpoints available in EMZI Nexus Booking.' }],
        meta: {},
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/metadata',
      description: 'Return application metadata and entity counts for Nexus Brain context.',
      auth: AUTH_BOTH,
      params: [],
      request_example: 'GET /api/mcp/v1/metadata',
      response_example: {
        success: true,
        message: null,
        data: {
          application: 'EMZI Nexus Booking',
          version: '1.0.0',
          entities: { resources: 12, bookings: 48, rooms: 3, transactions: 120, users: 15 },
        },
        meta: {},
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/resources',
      description: 'List or search bookable resources with filtering, sorting, and pagination.',
      auth: AUTH_BOTH,
      params: [
        { name: 'search', in: 'query', type: 'string', required: false, description: 'Search by name, type, or location' },
        { name: 'status', in: 'query', type: 'string', required: false, description: 'Filter by status: active, maintenance, inactive' },
        { name: 'resource_type', in: 'query', type: 'string', required: false, description: 'Filter by resource type' },
        ...PAGINATION_PARAMS,
        ...SORT_PARAMS,
      ],
      request_example: 'GET /api/mcp/v1/resources?search=van&status=active&page=1&per_page=50',
      response_example: {
        success: true,
        data: [{ id: 'abc-123', name: 'Company Van', resource_type: 'vehicle', status: 'active' }],
        meta: { current_page: 1, last_page: 1, per_page: 50, total: 1 },
      },
      error_examples: [...COMMON_ERRORS, { status: 403, message: 'Insufficient permissions.' }],
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/resources/{id}',
      description: 'Retrieve a single resource by ID including care summary.',
      auth: AUTH_BOTH,
      params: [{ name: 'id', in: 'path', type: 'string', required: true, description: 'Resource UUID' }],
      request_example: 'GET /api/mcp/v1/resources/abc-123',
      response_example: {
        success: true,
        data: { id: 'abc-123', name: 'Company Van', resource_type: 'vehicle', status: 'active', care_summary: { overdue: 0, due: 1, upcoming: 2 } },
        meta: {},
      },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Resource not found.' }],
    },
    {
      method: 'POST',
      path: '/api/mcp/v1/resources',
      description: 'Create a new bookable resource.',
      auth: AUTH_BOTH,
      params: [
        { name: 'name', in: 'body', type: 'string', required: true },
        { name: 'resource_type', in: 'body', type: 'string', required: true },
        { name: 'pricing_model', in: 'body', type: 'string', required: false, description: 'hourly, daily, or flat' },
        { name: 'rate', in: 'body', type: 'number', required: false },
        { name: 'status', in: 'body', type: 'string', required: false },
      ],
      request_example: 'POST /api/mcp/v1/resources {"name":"Meeting Room A","resource_type":"room","pricing_model":"hourly","rate":50}',
      response_example: { success: true, data: { id: 'new-id', name: 'Meeting Room A' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 403, message: 'Admin access required.' }],
    },
    {
      method: 'PATCH',
      path: '/api/mcp/v1/resources/{id}',
      description: 'Update an existing resource.',
      auth: AUTH_BOTH,
      params: [
        { name: 'id', in: 'path', type: 'string', required: true },
        { name: 'name', in: 'body', type: 'string', required: false },
        { name: 'status', in: 'body', type: 'string', required: false },
      ],
      request_example: 'PATCH /api/mcp/v1/resources/abc-123 {"status":"maintenance"}',
      response_example: { success: true, data: { id: 'abc-123', status: 'maintenance' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Resource not found.' }],
    },
    {
      method: 'DELETE',
      path: '/api/mcp/v1/resources/{id}',
      description: 'Delete a resource permanently.',
      auth: AUTH_BOTH,
      params: [{ name: 'id', in: 'path', type: 'string', required: true }],
      request_example: 'DELETE /api/mcp/v1/resources/abc-123',
      response_example: { success: true, data: { deleted: true }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Resource not found.' }],
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/bookings',
      description: 'List or search bookings with filtering, sorting, and pagination.',
      auth: AUTH_BOTH,
      params: [
        { name: 'search', in: 'query', type: 'string', required: false, description: 'Search title, resource name, or booker email' },
        { name: 'status', in: 'query', type: 'string', required: false, description: 'confirmed, cancelled, completed, pending, rejected' },
        { name: 'resource_id', in: 'query', type: 'string', required: false },
        { name: 'booked_by_email', in: 'query', type: 'string', required: false },
        { name: 'from', in: 'query', type: 'string', required: false, description: 'Start of date range (ISO 8601)' },
        { name: 'to', in: 'query', type: 'string', required: false, description: 'End of date range (ISO 8601)' },
        ...PAGINATION_PARAMS,
        ...SORT_PARAMS,
      ],
      request_example: 'GET /api/mcp/v1/bookings?status=confirmed&page=1&per_page=50',
      response_example: {
        success: true,
        data: [{ id: 'bk-1', title: 'Team offsite', status: 'confirmed', start_time: '2026-06-01T09:00:00.000Z' }],
        meta: { current_page: 1, last_page: 1, per_page: 50, total: 1 },
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/bookings/{id}',
      description: 'Retrieve a single booking by ID.',
      auth: AUTH_BOTH,
      params: [{ name: 'id', in: 'path', type: 'string', required: true }],
      request_example: 'GET /api/mcp/v1/bookings/bk-1',
      response_example: { success: true, data: { id: 'bk-1', title: 'Team offsite', status: 'confirmed' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Booking not found.' }],
    },
    {
      method: 'POST',
      path: '/api/mcp/v1/bookings',
      description: 'Create a new booking for a resource.',
      auth: AUTH_BOTH,
      params: [
        { name: 'resource_id', in: 'body', type: 'string', required: true },
        { name: 'title', in: 'body', type: 'string', required: true },
        { name: 'start_time', in: 'body', type: 'string', required: true, description: 'ISO 8601 datetime' },
        { name: 'end_time', in: 'body', type: 'string', required: true, description: 'ISO 8601 datetime' },
        { name: 'booked_by_email', in: 'body', type: 'string', required: false },
        { name: 'status', in: 'body', type: 'string', required: false },
      ],
      request_example: 'POST /api/mcp/v1/bookings {"resource_id":"abc-123","title":"Site visit","start_time":"2026-06-15T10:00:00Z","end_time":"2026-06-15T12:00:00Z"}',
      response_example: { success: true, data: { id: 'bk-new', status: 'pending' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 400, message: 'Resource cannot be booked.' }],
    },
    {
      method: 'PATCH',
      path: '/api/mcp/v1/bookings/{id}',
      description: 'Update a booking, typically to change status or times.',
      auth: AUTH_BOTH,
      params: [
        { name: 'id', in: 'path', type: 'string', required: true },
        { name: 'status', in: 'body', type: 'string', required: false },
        { name: 'start_time', in: 'body', type: 'string', required: false },
        { name: 'end_time', in: 'body', type: 'string', required: false },
      ],
      request_example: 'PATCH /api/mcp/v1/bookings/bk-1 {"status":"confirmed"}',
      response_example: { success: true, data: { id: 'bk-1', status: 'confirmed' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Booking not found.' }],
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/rooms',
      description: 'List or search meeting rooms with filtering and pagination.',
      auth: AUTH_BOTH,
      params: [
        { name: 'search', in: 'query', type: 'string', required: false },
        { name: 'status', in: 'query', type: 'string', required: false },
        { name: 'room_type', in: 'query', type: 'string', required: false },
        ...PAGINATION_PARAMS,
        ...SORT_PARAMS,
      ],
      request_example: 'GET /api/mcp/v1/rooms?status=active&page=1',
      response_example: {
        success: true,
        data: [{ id: 'rm-1', name: 'Boardroom', room_type: 'conference', status: 'active' }],
        meta: { current_page: 1, last_page: 1, per_page: 50, total: 1 },
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/rooms/{id}',
      description: 'Retrieve a single room by ID.',
      auth: AUTH_BOTH,
      params: [{ name: 'id', in: 'path', type: 'string', required: true }],
      request_example: 'GET /api/mcp/v1/rooms/rm-1',
      response_example: { success: true, data: { id: 'rm-1', name: 'Boardroom' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Room not found.' }],
    },
    {
      method: 'POST',
      path: '/api/mcp/v1/rooms',
      description: 'Create a new meeting room.',
      auth: AUTH_BOTH,
      params: [{ name: 'name', in: 'body', type: 'string', required: true }],
      request_example: 'POST /api/mcp/v1/rooms {"name":"Studio B","room_type":"studio"}',
      response_example: { success: true, data: { id: 'rm-new', name: 'Studio B' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 403, message: 'Admin access required.' }],
    },
    {
      method: 'PATCH',
      path: '/api/mcp/v1/rooms/{id}',
      description: 'Update an existing room.',
      auth: AUTH_BOTH,
      params: [
        { name: 'id', in: 'path', type: 'string', required: true },
        { name: 'name', in: 'body', type: 'string', required: false },
        { name: 'status', in: 'body', type: 'string', required: false },
      ],
      request_example: 'PATCH /api/mcp/v1/rooms/rm-1 {"status":"maintenance"}',
      response_example: { success: true, data: { id: 'rm-1', status: 'maintenance' }, meta: {} },
      error_examples: [...COMMON_ERRORS, { status: 404, message: 'Room not found.' }],
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/transactions',
      description: 'List credit transactions with filtering and pagination.',
      auth: AUTH_BOTH,
      params: [
        { name: 'user_email', in: 'query', type: 'string', required: false },
        { name: 'type', in: 'query', type: 'string', required: false },
        { name: 'search', in: 'query', type: 'string', required: false },
        ...PAGINATION_PARAMS,
        ...SORT_PARAMS,
      ],
      request_example: 'GET /api/mcp/v1/transactions?user_email=jane@example.com&page=1',
      response_example: {
        success: true,
        data: [{ id: 'tx-1', user_email: 'jane@example.com', type: 'top_up', amount_cents: 5000 }],
        meta: { current_page: 1, last_page: 1, per_page: 50, total: 1 },
      },
      error_examples: [...COMMON_ERRORS, { status: 403, message: 'Insufficient permissions.' }],
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/care/schedules',
      description: 'List resource care and upkeep schedules across all resources.',
      auth: AUTH_BOTH,
      params: [
        { name: 'status', in: 'query', type: 'string', required: false, description: 'overdue, due, upcoming, or ok' },
        { name: 'resource_type', in: 'query', type: 'string', required: false },
        { name: 'category', in: 'query', type: 'string', required: false },
        { name: 'search', in: 'query', type: 'string', required: false },
        ...PAGINATION_PARAMS,
      ],
      request_example: 'GET /api/mcp/v1/care/schedules?status=overdue&page=1',
      response_example: {
        success: true,
        data: [{ id: 'care-1', resource_name: 'Company Van', label: 'Oil change', status: 'overdue' }],
        meta: { current_page: 1, last_page: 1, per_page: 50, total: 1 },
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'GET',
      path: '/api/mcp/v1/care/summary',
      description: 'Return global care schedule summary counts (overdue, due, upcoming).',
      auth: AUTH_BOTH,
      params: [],
      request_example: 'GET /api/mcp/v1/care/summary',
      response_example: {
        success: true,
        data: { overdue: 2, due: 5, upcoming: 12, total_active: 45 },
        meta: {},
      },
      error_examples: COMMON_ERRORS,
    },
    {
      method: 'POST',
      path: '/api/sso/nexus/verify',
      description: 'Validate a Nexus Brain SSO JWT and issue a local session token for the booking app.',
      auth: AUTH_KEY,
      params: [
        { name: 'token', in: 'body', type: 'string', required: true, description: 'Signed Nexus JWT' },
        { name: 'redirect_to', in: 'body', type: 'string', required: false },
      ],
      request_example: 'POST /api/sso/nexus/verify {"token":"<nexus-jwt>"}',
      response_example: {
        token: '<local-jwt>',
        user: { id: 'user-1', email: 'jane@example.com' },
        redirect_to: 'http://localhost:5173',
      },
      error_examples: [
        { status: 401, message: 'Invalid or expired token.' },
        { status: 422, message: 'SSO is not configured.' },
      ],
    },
  ];
}
